### ISSUE TITLE
require 'libsvm' fails (MS windows)

### ISSUE THREAD

**Issue by jeppevb** [febeling/rb-libsvm#10]
I've installed ruby, devkit and rubygems and sucessfully installed the rb-libsvm gem. When I try to run the examples or go require 'libsvm' in irb i get this:

<pre>
C:\dev>ruby
require 'libsvm'
^Z
c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': 193: %1 is not a valid Win32 application.   - c:/dev/ruby193/lib/ruby/gems/1.9.1/gems/rb-libsvm-1.0.8/lib/libsvm/libsvm_ext.so (LoadError)
        from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from c:/dev/ruby193/lib/ruby/gems/1.9.1/gems/rb-libsvm-1.0.8/lib/libsvm.rb:2:in `<top (required)>'
        from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from -:1:in `<main>'
</pre>

**Comment by febeling** [comment]
Just saw that rake-compiler has support for cross-compiling now, and also provides a special `rake-compiler-dev-box` VM for this. Might make implementing this thing easier.

https://github.com/rake-compiler/rake-compiler#cross-compilation---the-future-is-now

**Comment by febeling** [comment]
I don't find the time to do this. So the new status pretty much is: PR welcome.

**Comment by georgeu2000** [comment]
@jeppevb - Not really an answer to your issue, but I'll share with you my experience. Using Ruby on Windows makes it more difficult than Mac or Ubuntu. I suggest installing Ubuntu in Windows. It is very simple and you do not need dual boot.

**Comment by Kraviscloud** [comment]
> I've installed ruby, devkit and rubygems and sucessfully installed the rb-libsvm gem. When I try to run the examples or go require 'libsvm' in irb i get this:
> 
> C:\dev>ruby
> require 'libsvm'
> ^Z
> c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': 193: %1 is not a valid Win32 application.   - c:/dev/ruby193/lib/ruby/gems/1.9.1/gems/rb-libsvm-1.0.8/lib/libsvm/libsvm_ext.so (LoadError)
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
>         from c:/dev/ruby193/lib/ruby/gems/1.9.1/gems/rb-libsvm-1.0.8/lib/libsvm.rb:2:in `'
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
>         from -:1:in `'

Gp

**Comment by Kraviscloud** [comment]
> I've installed ruby, devkit and rubygems and sucessfully installed the rb-libsvm gem. When I try to run the examples or go require 'libsvm' in irb i get this:
> 
> C:\dev>ruby
> require 'libsvm'
> ^Z
> c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': 193: %1 is not a valid Win32 application.   - c:/dev/ruby193/lib/ruby/gems/1.9.1/gems/rb-libsvm-1.0.8/lib/libsvm/libsvm_ext.so (LoadError)
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
>         from c:/dev/ruby193/lib/ruby/gems/1.9.1/gems/rb-libsvm-1.0.8/lib/libsvm.rb:2:in `'
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
>         from c:/dev/ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
>         from -:1:in `'

Gp

**Comment by febeling** [comment]
@Kraviscloud What is gp?
